version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t netkuy/web-app:$CIRCLE_BUILD_NUM .
      - run: docker push netkuy/web-app:$CIRCLE_BUILD_NUM
